---
platform: emscripten 
generator: Unix Makefiles 
build_tool: make
build_type: Debug
cmake-toolchain: emscripten.toolchain.cmake
defines:
    FIPS_NO_ASSERTS_IN_RELEASE: ON
    FIPS_EMSCRIPTEN_USE_WASM: ON
    FIPS_EMSCRIPTEN_MEM_INIT_METHOD: 0
    FIPS_EMSCRIPTEN_USE_EMMALLOC: ON
    FIPS_EMSCRIPTEN_RELATIVE_SHELL_HTML: "src/shell.html"


